### ISSUE TITLE
how use persian-faker in Factory Class

### ISSUE THREAD

**Issue by nO-sPeak** [mohammadsalmani28/faker#1]
Hi, i tried few hours to use your package in my Factory class with no luck.
can you make an example how i should use it inside a Factory class ?
is it possible to use both English faker and persian faker at the same time in factory class?

**Comment by mohammadsalmani28** [comment]
Hi remember to use class in your factory at first:
`
use Mohammadsalmani28\Faker\Faker;
`
and then you can use it like this:
`$faker = new Faker();
$name = $faker->name();
$firstName = $name->firstName;
$lastName = $name->lastName;`


Another way is how i explain in documents...

@nO-sPeak
